### ISSUE TITLE
No docs?

### ISSUE THREAD

**Issue by rickhuizinga** [angular/angular-carousel#3]
It's hard to get started with this when there is no docs, demo or statement of capabilities.

**Comment by jboothe** [comment]
+1

**Comment by bshepherdson** [comment]
This was an early attempt at carousel functionality @jeffbcross and I wrote a long time ago. Since that time, a more flexible and much better-documented carousel directive was developed by a community member, see [here](https://github.com/revolune/angular-carousel).

**Comment by jboothe** [comment]
Thanks for the heads up, shepheb. There was a typo in the link. Here's the correct link:
https://github.com/revolunet/angular-carousel
