### ISSUE TITLE
unregister from bower

### ISSUE THREAD

**Issue by revolunet** [angular/angular-carousel#4]
Hi guys,

the "angular-carousel" bower still points here, i guess it would be better to point it to a working version ? could you please unregister that name from bower ?

thanks

**Comment by revolunet** [comment]
or, better, i could push here directly :)

**Comment by lauterry** [comment]
+1 

Please unregister the name "angular-carousel" from bower.

I think "angular-carousel" should point to @revolunet 's angular-carousel instead.

**Comment by 0x-r4bbit** [comment]
Agreed!

**Comment by jeffbcross** [comment]
Submitted request. Sorry I didn't see this issue pop up! And thanks to @revolunet for tweeting me about it ;)

**Comment by revolunet** [comment]
thanks @jeffbcross :)

**Comment by lauterry** [comment]
Yeah \o/ Thanks @jeffbcross

**Comment by rwjblue** [comment]
Removed from Bower.

**Comment by jeffbcross** [comment]
Thanks Robert!

**Comment by revolunet** [comment]
thanks guys
